Revert "Add the inclued for RGB keys"
Build fails with:
/tmp/zmk-config/zmk/app/src/rgb_underglow.c:252: undefined reference to `__device_dts_ord_149'

This reverts commit cc0c5fa9d33d0beebd86c9c0aa242d64f4b4b94e.